title: "omnes-flores Technology Preview"
author: "Megagon Labs, Tokyo."
email: "ginza@megagon.ai"
description: "A unified NLP framework for LLMs."
github_username: "megagonlabs"
twitter_username: "MegagonLabs"
remote_theme: "jekyll/minima@1e8a445"
