title: "omnes-flores: A Unified NLP Framework for LLMs"
author:
  name: megagonlabs
  email: ginza@megagon.ai
remote_theme: jekyll/minima@d4d779a
plugins:
  - jekyll-feed
  - jekyll-seo-tag
minima:
  social_links:
    - title: Megagon Labs
      icon: github
      url: "https://github.com/megagonlabs"
    - title: Megagon Labs
      icon: x-twitter
      url: "https://x.com/MegagonLabs"
